### ISSUE TITLE
Please include dotfiles of the bar as well

### ISSUE THREAD

**Issue by ghost** [taylor85345/hyprland-dotfiles#2]
Lovely rice , could you please include dotfiles of the bar as well ?

**Comment by taylor85345** [comment]
The bar config is in a [subdirectory of the hyprland config](https://github.com/taylor85345/garden-hyprland-dotfiles/tree/master/hypr/bar). Several of the scripts are hyprland-specific, so I figured it made more sense to keep it separate from the main eww configs in case users already had a config for a different wm.

The eww daemon should automatically start, and all autostarts and keybinds point to the correct config directory.

**Comment by ghost** [comment]
i see, thank you
