### ISSUE TITLE
How to create ascii format file like leaf.ascii?

### ISSUE THREAD

**Issue by hyq12358** [taylor85345/hyprland-dotfiles#3]

**Comment by taylor85345** [comment]
I found a simple graphic of a leaf online and ran it through `im2a` to convert to ascii text. I only did it the one time over a year ago, so I don't recall all of the details, but I think you can just direct the output from im2a to a text file and it will work.

**Comment by hyq12358** [comment]
> I found a simple graphic of a leaf online and ran it through `im2a` to convert to ascii text. I only did it the one time over a year ago, so I don't recall all of the details, but I think you can just direct the output from im2a to a text file and it will work.

OK. Thank you.
