### ISSUE TITLE
Pipewire or Pulseaudio 

### ISSUE THREAD

**Issue by Silverfox28** [taylor85345/hyprland-dotfiles#4]
Please, do you have install Pipewire or Pulseaudio?

**Comment by taylor85345** [comment]
I don't believe anything in my configs is dependent on one or the other, but for Wayland in general you will likely have a better experience with Pipewire if you do anything with video/screen capture. I believe the volume module in my eww bar uses pamixer, which works with either but might need some tweaks for something like a pure ALSA setup.

**Comment by Silverfox28** [comment]
ok, thank you
